[package]
authors = ["MamoruDS <mamoruds.io@gmail.com>"]
description = "A simple formatter for Silq"
edition = "2018"
license = "MIT"
name = "silqfmt"
readme = "README.md"
repository = "https://github.com/MamoruDS/silqfmt"
version = "0.1.1"

[dependencies]
clap = "2.33.1"
regex = "1"
